---
title: "ST2195_220460376 Part 1"
author: "carine"
date: "`r Sys.Date()`"
output: html_document
---

# ST2195 Programming for Data Science Coursework Part 1

This R Markdown analysis involves implementing the Metropolis-Hastings algorithm, a Markov Chain Monte Carlo (MCMC) technique, to produce a sequence of random numbers drawn from a specified probability density function.


a. Random Walk Metropolis Algorithm
```{r}
#Establish probability density function (PDF), f(x)
pdf_f <- function(x) {
  return(0.5 * exp(-abs(x)))
}
```

```{r}
#Calibrate variables
N <- 10000
s <- 1
```

```{r}
#Execute the Random Walk Metropolis 
RWM <- function(N, s) {
  samplesx <- numeric(N)       
  samplesx[1] <- rnorm(1)  
  
  for (i in 2:N) {
    xalpha <- rnorm(1, mean = samplesx[i-1], sd = s)  #Implement a new sample
    log_alpha <- log(pdf_f(xalpha)) - log(pdf_f(samplesx[i-1]))  #Calculate the log acceptance ratio
    
    if (log(runif(1)) < log_alpha) {
      samplesx[i] <- xalpha  #Accept the proposed sample
    } else {
      samplesx[i] <- samplesx[i-1]  #Reject and keep the current sample
    }
  }
  
  return(samplesx)
}
```

```{r}
#Run the Random Walk Metropolis algorithm
samplesx <- RWM(N, s)
```

```{r}
#Define the true distribution
valuex <- seq(min(samplesx), max(samplesx), length.out = 1000)
true_density <- pdf_f(valuex)
```

```{r}
#Plot histogram and kernel density 

#Histogram
hist(samplesx, breaks = 50, freq = FALSE, col = "lightslateblue", xlim = c(-10, 10), ylim = c(0, 0.55), main = "Random Walk Metropolis", xlab = "Values", ylab = "Density")

#Kernel Density
lines(density(samplesx), col = "red", lwd = 1.5)

#True Distribution
curve(0.5 * exp(-abs(x)), from = -10, to = 10, add = TRUE, col = "darkgreen", lty = "dashed", lwd = 1.5)

#Add legends
legend("topright", legend = c("Histogram", "Kernel Density", "f(x)"), fill = c("lightslateblue", "red", "darkgreen"), lty = c(0, 1, 3))

```

```{r}
#Compute sample mean and sample standard deviation
s_mean <- mean(samplesx)
s_std <- sd(samplesx)

#Print sample mean and sample standard deviation
print(paste("Sample Mean:", s_mean))
print(paste("Sample Standard Deviation:", s_std))
```


b. R-hat value
```{r}
#Define a procedure to generate chains
chain_generate <- function(N, J, s) {
  chain <- list()
  for (j in 1:J) {
    x0_j <- runif(1)  #Initial value for chain j
    j_chain <- numeric(N + 1)  #Initialise the chain with the initial value
    j_chain[1] <- x0_j
    for (i in 2:(N + 1)) {
      xbeta <- j_chain[i - 1] + rnorm(1, 0, s)  #Define Random Walk Metropolis
      j_chain[i] <- xbeta
    }
    chain[[j]] <- j_chain
  }
  return(chain)
}
```

```{r}
#Establish and compute Mj as
s_mean <- function(chain) {
  Mj <- sapply(chain, mean)
  return(Mj)
}

#Establish and compute Vj as
w_s_var <- function(chain, Mj) {
  Vj <- sapply(chain, function(chain) {
    var(chain)
  })
  return(Vj)
}

#Establish and compute W as
ow_s_var <- function(Vj) {
  W <- mean(Vj)
  return(W)
}

#Establish and compute M as
o_s_mean <- function(Mj) {
  M <- mean(Mj)
  return(M)
}

#Establish and compute B as
b_s_var <- function(Mj, M) {
  B <- N / (J - 1) * sum((Mj - M)^2)
  return(B)
}

#Establish a procedure to compute R-hat
R_hat_calculation <- function(B, W) {
  Rnumber <- sqrt((W + B) / W)
  return(Rnumber)
}
```

```{r}
#Define variables
N <- 2000  
J <- 4     
s_value <- seq(0.001, 1, length.out = 100) 
valueR_hat <- numeric(length(s_value))
```

```{r}
#Compute the R-hat statistic for each value of s
for (i in seq_along(s_value)) {
  s <- s_value[i]
  chain <- chain_generate(N, J, s)
  Mj <- s_mean(chain)
  M <- o_s_mean(Mj)
  Vj <- w_s_var(chain, Mj)
  W <- ow_s_var(Vj)
  B <- b_s_var(Mj, M)
  valueR_hat[i] <- R_hat_calculation(B, W)
}
```

```{r}
#Map R-hat values against s values
plot(s_value, valueR_hat, type = "l", col = "blue", 
     xlab = "s", ylab = expression(hat(R)), 
     main = expression("Plot of " ~ hat(R) ~ " values against s values"))

abline(h = 1.05, col = "red", lty = 2)

legend("topright", legend = c(expression(hat(R)~"values"), "Asymptote (1.05)"), 
       lty = c(1, 2), col = c("blue", "red"))
```